Работа с файлами
brominchic/spring-lessons pull request #7
Opened 2024-10-16 23:14 UTC by brominchic

2024-10-17 06:32 UTC, kampaii53 requested changes

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    private final FileJpaComponent jpaComponent;
не надо везде Jpa цеплять как суффикс

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    @GetMapping("/download/{filename:.+}")
:.+ - что делает?

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    public void uploadFile(@RequestParam("id") Long id, @RequestParam("file") MultipartFile file, @RequestParam("userId") Long userId) throws IOException {
загрузка у тебя должна возвращать идентификатор, под которым файл сохранился

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/model/dto/FileDto.java
> +public class FileDto {
не вижу где используется

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/service/component/mapper/AccountMapper.java
> -    public AccountDto stringToDto(String string) throws JsonProcessingException {
эти изменения у тебя не должны включаться в текщую задачу

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/service/component/mapper/AccountTypeMapper.java
> -    public AccountTypeDto stringToDto(String string) throws JsonProcessingException {
почему эти изменения включены? они не соответствуют задаче

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/service/component/mapper/FileMapper.java
> +    public File entityToFile(FileEntity entity) throws IOException {
зачем тебе маппинг в файл?
поясню, File - у тебя в системе создается и живет, для прокачивания через приложение он тебе не нужен

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/service/jpa/FileJpaComponent.java
> +                .id(id)
id должен быть автогенерирован

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/service/jpa/FileJpaComponent.java
> +        repository.save(mapper.dtoToEntity(dto));
лол, зачем ты здесь двойную работу делаешь? собери сразу entity нужную

2024-10-17 06:32 UTC, kampaii53 commented on src/main/java/com/example/spring/service/jpa/FileJpaComponent.java
> +        File file = mapper.entityToFile(repository.findByFilename(filename).orElseThrow());
не работай с File здесь. тебе надо вернуть байты файла

2024-10-17 06:32 UTC, kampaii53 commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changelogs/new-table.sql
как ты потом поймешь что этот ченджлог создает именно файловую таблицу? имена должны быть понятными

2024-10-17 09:05 UTC, brominchic commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    @GetMapping("/download/{filename:.+}")
.+ - любое количество символов, регулярное выражение

2024-10-19 11:34 UTC, brominchic commented on src/main/java/com/example/spring/service/component/mapper/AccountTypeMapper.java
> -    public AccountTypeDto stringToDto(String string) throws JsonProcessingException {
надо было до этого убрать еще, вернуть обратно эти методы?

2024-10-19 11:47 UTC, brominchic commented on src/main/java/com/example/spring/model/dto/FileDto.java
> +public class FileDto {
нигде получается

2024-10-19 11:50 UTC, brominchic commented on src/main/java/com/example/spring/model/dto/FileDto.java
> +public class FileDto {
как и маппер

2024-10-21 10:39 UTC, kampaii53 commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    @GetMapping("/download/{filename:.+}")
мы с тобой еще валидацию не проходили, ты это где откопал?

2024-10-21 10:43 UTC, kampaii53 requested changes

2024-10-21 10:43 UTC, kampaii53 commented on src/main/java/com/example/spring/controller/FileController.java
> +    private final FileComponent jpaComponent;
если это fileComponent то почему имя jpa осталось

2024-10-21 10:43 UTC, kampaii53 commented on src/main/java/com/example/spring/service/component/mapper/AccountMapper.java
> -    public AccountDto stringToDto(String string) throws JsonProcessingException {
и что? в итоге изменения так и остались в данном МР

2024-10-21 10:43 UTC, kampaii53 commented on src/main/java/com/example/spring/service/component/mapper/AccountTypeMapper.java
> -    public AccountTypeDto stringToDto(String string) throws JsonProcessingException {
да. отдельным МР сделай удаление если так надо

2024-10-21 10:43 UTC, kampaii53 commented on src/main/java/com/example/spring/service/jpa/FileComponent.java
> +        FileEntity entity = FileEntity.builder().userEntity(UserEntity.builder().id(userId).build()).fileData(file.getBytes()).filename(file.getOriginalFilename()).build();
когда билдер используешь каждое поле пиши с новой строки чтобы легче читать было

2024-10-21 10:43 UTC, kampaii53 commented on src/main/resources/db/changelog/changelogs/file-sequence.sql
> +CREATE SEQUENCE public.id_seq
это можно в один скрипт с file-table добавить

2024-10-26 14:21 UTC, brominchic commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    @GetMapping("/download/{filename:.+}")
в питоне для егэ использовал

2024-10-26 14:34 UTC, brominchic commented on src/main/java/com/example/spring/controller/FileJpaController.java
> +    @GetMapping("/download/{filename:.+}")
https://spring.io/guides/gs/uploading-files , конкретно это отсюда, а на регулярных выражениях некоторые задания из егэ делаются

2024-10-26 15:17 UTC, brominchic commented on src/main/java/com/example/spring/service/component/mapper/AccountMapper.java
> -    public AccountDto stringToDto(String string) throws JsonProcessingException {
вернул

2024-10-26 15:17 UTC, brominchic commented on src/main/java/com/example/spring/controller/FileController.java
> +    private final FileComponent jpaComponent;
убрал

2024-11-09 08:58 UTC, kampaii53 requested changes

2024-11-09 08:58 UTC, kampaii53 commented on src/main/java/com/example/spring/service/component/mapper/Mapper.java
> +    D entityToDto(E entity) throws IOException;
странно получилось, тебе не кажется? что абстрактный класс конкретный экепшн может выбросить. в данном  случае считаю некорректно

2024-11-09 08:58 UTC, kampaii53 commented on src/main/java/com/example/spring/service/jpa/FileComponent.java
> +        FileEntity entity = FileEntity.builder().userEntity(UserEntity.builder().id(userId).build()).fileData(file.getBytes()).filename(file.getOriginalFilename()).build();
билдер я тебя просил с переносами

2024-11-10 11:01 UTC, kampaii53 commented on src/main/java/com/example/spring/service/jpa/FileComponent.java
> +                .userEntity(UserEntity
![изображение](https://github.com/user-attachments/assets/1fb7bb39-7855-4b48-8fa7-71bc8eaef722)
красным неправильно, зеленым правильно

2024-11-10 12:07 UTC, merged